enum UserRole {
   USER
   PRACTITIONER
}

type User {
   email: String! @unique
   role: UserRole!
   name: String
   firstName: String
   lastName: String
   picture: String
   about: String
   home: String
   works: String
   onboarded: Boolean
   activities: [Activity] @relation
}

type Activity {
   title: String!
   description: String!
   images: [String]
   duration: Int!
   date: String!
   repeat: String
   active: Boolean!
   user: User!
}


type Query {
   findUserByEmail(email: String!): User 
   allActiveActivities(active: Boolean!): [Activity!]
}
